name: thecoffeehouse_api
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  json_annotation: ^4.4.0
  logger: any
  retrofit: ^3.0.1

dev_dependencies:
  build_runner: ^2.0.0
  coverage: ^1.0.3
  json_serializable: ^6.0.0
  mocktail: ^0.2.0
  retrofit_generator: ^4.0.1
  test: ^1.16.4
  very_good_analysis: ^2.4.0
